apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fake-load-1
  name: fake-load-1
  namespace: fake-load
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fake-load-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fake-load-1
    spec:
      containers:
      - env:
        - name: --env
          value: "128"
        - name: THREADS_TO_RUN
          value: "1"
        image: registry.hub.docker.com/gregclinker/fake-load:0.1
        imagePullPolicy: IfNotPresent
        name: fake-load
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30